package routes

import (
	"log"

	configs "apotek-clean/configs"
	middlewares "apotek-clean/middlewares"
	export_services "apotek-clean/services/exports"
	excel_audits "apotek-clean/services/exports/excel/audits"
	excel_masters "apotek-clean/services/exports/excel/masters"
	excel_reports "apotek-clean/services/exports/excel/reports"
	excel_systems "apotek-clean/services/exports/excel/systems"
	excel_transactions "apotek-clean/services/exports/excel/transactions"
	pdf_audits "apotek-clean/services/exports/pdf/audits"
	pdf_masters "apotek-clean/services/exports/pdf/masters"
	pdf_transactions "apotek-clean/services/exports/pdf/transactions"
	fiber "github.com/gofiber/fiber/v2"
)

func RegisterExportRoutes(app *fiber.App) {
	log.Println("[Route] Initializing internal export routes")

	excelService := export_services.NewExcelServices(configs.DB)
	excelProductHandler := excel_masters.NewExcelProductHandler(excelService)
	excelUnitHandler := excel_masters.NewExcelUnitHandler(excelService)
	excelProductCategoryHandler := excel_masters.NewExcelProductCategoryHandler(excelService)
	excelUnitConversionHandler := excel_masters.NewExcelUnitConversionHandler(excelService)
	excelSupplierHandler := excel_masters.NewExcelSupplierHandler(excelService)
	excelSupplierCategoryHandler := excel_masters.NewExcelSupplierCategoryHandler(excelService)
	excelMemberCategoryHandler := excel_masters.NewExcelMemberCategoryHandler(excelService)
	excelMemberHandler := excel_masters.NewExcelMemberHandler(excelService)
	excelFirstStockHandler := excel_audits.NewExcelFirstStockHandler(excelService)
	excelOpnameHandler := excel_audits.NewExcelOpnameHandler(excelService)
	excelFirstStockItemHandler := excel_audits.NewExcelFirstStockItemHandler(excelService)
	excelOpnameItemHandler := excel_audits.NewExcelOpnameItemHandler(excelService)
	excelPurchaseHandler := excel_transactions.NewExcelPurchaseHandler(excelService)
	excelSaleHandler := excel_transactions.NewExcelSaleHandler(excelService)
	excelDuplicateReceiptHandler := excel_transactions.NewExcelDuplicateReceiptHandler(excelService)
	excelBuyReturnHandler := excel_transactions.NewExcelBuyReturnHandler(excelService)
	excelSaleReturnHandler := excel_transactions.NewExcelSaleReturnHandler(excelService)
	excelExpenseHandler := excel_transactions.NewExcelExpenseHandler(excelService)
	excelAnotherIncomeHandler := excel_transactions.NewExcelAnotherIncomeHandler(excelService)
	excelPurchaseItemHandler := excel_transactions.NewExcelPurchaseItemHandler(excelService)
	excelSaleItemHandler := excel_transactions.NewExcelSaleItemHandler(excelService)
	excelDuplicateReceiptItemHandler := excel_transactions.NewExcelDuplicateReceiptItemHandler(excelService)
	excelBuyReturnItemHandler := excel_transactions.NewExcelBuyReturnItemHandler(excelService)
	excelSaleReturnItemHandler := excel_transactions.NewExcelSaleReturnItemHandler(excelService)
	excelDailyAssetHandler := excel_systems.NewExcelDailyAssetHandler(excelService)
	excelDefectaHandler := excel_systems.NewExcelDefectaHandler(excelService)
	excelNearedReportHandler := excel_systems.NewExcelNearedReportHandler(excelService)
	excelTopSellingHandler := excel_systems.NewExcelTopSellingHandler(excelService)
	excelLeastSellingHandler := excel_systems.NewExcelLeastSellingHandler(excelService)
	excelNeracaSaldoHandler := excel_reports.NewExcelNeracaSaldoHandler(excelService)

	pdfService := export_services.NewPDFService(configs.DB)
	pdfProductHandler := pdf_masters.NewPdfProductHandler(pdfService)
	pdfUnitHandler := pdf_masters.NewPdfUnitHandler(pdfService)
	pdfProductCategoryHandler := pdf_masters.NewPdfProductCategoryHandler(pdfService)
	pdfUnitConversionHandler := pdf_masters.NewPdfUnitConversionHandler(pdfService)
	pdfSupplierHandler := pdf_masters.NewPdfSupplierHandler(pdfService)
	pdfSupplierCategoryHandler := pdf_masters.NewPdfSupplierCategoryHandler(pdfService)
	pdfMemberCategoryHandler := pdf_masters.NewPdfMemberCategoryHandler(pdfService)
	pdfMemberHandler := pdf_masters.NewPdfMemberHandler(pdfService)
	pdfFirstStockHandler := pdf_audits.NewPdfFirstStockHandler(pdfService)
	pdfOpnameHandler := pdf_audits.NewPdfOpnameHandler(pdfService)
	pdfFirstStockItemHandler := pdf_audits.NewPdfFirstStockItemHandler(pdfService)
	pdfOpnameItemHandler := pdf_audits.NewPdfOpnameItemHandler(pdfService)
	pdfPurchaseItemHandler := pdf_transactions.NewPdfPurchaseItemHandler(pdfService)
	pdfSaleItemHandler := pdf_transactions.NewPdfSaleItemHandler(pdfService)
	pdfBuyReturnItemHandler := pdf_transactions.NewPdfBuyReturnItemHandler(pdfService)
	pdfSaleReturnItemHandler := pdf_transactions.NewPdfSaleReturnItemHandler(pdfService)
	pdfDuplicateReceiptItemHandler := pdf_transactions.NewPdfDuplicateReceiptItemHandler(pdfService)
	pdfPurchaseHandler := pdf_transactions.NewPdfPurchaseHandler(pdfService)
	pdfSaleHandler := pdf_transactions.NewPdfSaleHandler(pdfService)
	pdfBuyReturnHandler := pdf_transactions.NewPdfBuyReturnHandler(pdfService)
	pdfSaleReturnHandler := pdf_transactions.NewPdfSaleReturnHandler(pdfService)
	pdfDuplicateReceiptHandler := pdf_transactions.NewPdfDuplicateReceiptHandler(pdfService)
	pdfExpenseHandler := pdf_transactions.NewPdfExpenseHandler(pdfService)
	pdfAnotherIncomeHandler := pdf_transactions.NewPdfAnotherIncomeHandler(pdfService)
	pdfProductLabelHandler := pdf_masters.NewPdfProductLabelHandler(pdfService)

	app.Get("/api/products/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelProductHandler.ExportExcel)
	app.Get("/api/units/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelUnitHandler.ExportExcel)
	app.Get("/api/product-categories/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelProductCategoryHandler.ExportExcel)
	app.Get("/api/unit-conversions/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelUnitConversionHandler.ExportExcel)
	app.Get("/api/suppliers/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelSupplierHandler.ExportExcel)
	app.Get("/api/supplier-categories/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelSupplierCategoryHandler.ExportExcel)
	app.Get("/api/member-categories/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelMemberCategoryHandler.ExportExcel)
	app.Get("/api/members/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelMemberHandler.ExportExcel)
	app.Get("/api/first-stocks/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelFirstStockHandler.ExportExcel)
	app.Get("/api/opnames/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelOpnameHandler.ExportExcel)
	app.Get("/api/first-stock-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelFirstStockItemHandler.ExportExcel)
	app.Get("/api/opname-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelOpnameItemHandler.ExportExcel)
	app.Get("/api/purchases/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelPurchaseHandler.ExportExcel)
	app.Get("/api/sales/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelSaleHandler.ExportExcel)
	app.Get("/api/duplicate-receipts/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelDuplicateReceiptHandler.ExportExcel)
	app.Get("/api/buy-returns/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelBuyReturnHandler.ExportExcel)
	app.Get("/api/sale-returns/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelSaleReturnHandler.ExportExcel)
	app.Get("/api/expenses/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelExpenseHandler.ExportExcel)
	app.Get("/api/another-incomes/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelAnotherIncomeHandler.ExportExcel)
	app.Get("/api/purchase-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelPurchaseItemHandler.ExportExcel)
	app.Get("/api/sale-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelSaleItemHandler.ExportExcel)
	app.Get("/api/duplicate-receipt-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelDuplicateReceiptItemHandler.ExportExcel)
	app.Get("/api/buy-return-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelBuyReturnItemHandler.ExportExcel)
	app.Get("/api/sale-return-items/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelSaleReturnItemHandler.ExportExcel)
	app.Get("/api/daily-assets/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelDailyAssetHandler.ExportExcel)
	app.Get("/api/defectas/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelDefectaHandler.ExportExcel)
	app.Get("/api/dashboard/neared-report/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelNearedReportHandler.ExportExcel)
	app.Get("/api/dashboard/top-selling-report/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelTopSellingHandler.ExportExcel)
	app.Get("/api/dashboard/least-selling-report/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelLeastSellingHandler.ExportExcel)
	app.Get("/api/reports/neraca-saldo/excel", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), excelNeracaSaldoHandler.ExportExcel)

	app.Get("/api/product-label/:id", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfProductLabelHandler.ExportPDF)
	app.Get("/api/products/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfProductHandler.ExportPDF)
	app.Get("/api/units/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfUnitHandler.ExportPDF)
	app.Get("/api/product-categories/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfProductCategoryHandler.ExportPDF)
	app.Get("/api/unit-conversions/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfUnitConversionHandler.ExportPDF)
	app.Get("/api/suppliers/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfSupplierHandler.ExportPDF)
	app.Get("/api/supplier-categories/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfSupplierCategoryHandler.ExportPDF)
	app.Get("/api/member-categories/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfMemberCategoryHandler.ExportPDF)
	app.Get("/api/members/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfMemberHandler.ExportPDF)
	app.Get("/api/first-stocks/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfFirstStockHandler.ExportPDF)
	app.Get("/api/opnames/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfOpnameHandler.ExportPDF)
	app.Get("/api/first-stock-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfFirstStockItemHandler.ExportPDF)
	app.Get("/api/opname-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfOpnameItemHandler.ExportPDF)
	app.Get("/api/purchase-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfPurchaseItemHandler.ExportPDF)
	app.Get("/api/sale-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfSaleItemHandler.ExportPDF)
	app.Get("/api/buy-return-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfBuyReturnItemHandler.ExportPDF)
	app.Get("/api/sale-return-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfSaleReturnItemHandler.ExportPDF)
	app.Get("/api/duplicate-receipt-items/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfDuplicateReceiptItemHandler.ExportPDF)
	app.Get("/api/purchases/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfPurchaseHandler.ExportPDF)
	app.Get("/api/sales/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfSaleHandler.ExportPDF)
	app.Get("/api/duplicate-receipts/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfDuplicateReceiptHandler.ExportPDF)
	app.Get("/api/buy-returns/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfBuyReturnHandler.ExportPDF)
	app.Get("/api/sale-returns/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfSaleReturnHandler.ExportPDF)
	app.Get("/api/expenses/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfExpenseHandler.ExportPDF)
	app.Get("/api/another-incomes/pdf", middlewares.JWTMiddleware, middlewares.RoleMiddleware("administrator", "operator", "cashier", "finance", "superadmin"), pdfAnotherIncomeHandler.ExportPDF)
}
